// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2SMessage.proto

package com.wangboo.nsgame.protocol;

public final class C2SMessageProto {
  private C2SMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2SMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.wangboo.nsgame.protocol.MessageId msgId = 1;
    /**
     * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
     */
    com.wangboo.nsgame.protocol.MessageProto.MessageId getMsgId();

    // optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;
    /**
     * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
     */
    boolean hasC2SLogin();
    /**
     * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
     */
    com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin getC2SLogin();
    /**
     * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
     */
    com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder getC2SLoginOrBuilder();
  }
  /**
   * Protobuf type {@code com.wangboo.nsgame.protocol.C2SMessage}
   */
  public static final class C2SMessage extends
      com.google.protobuf.GeneratedMessage
      implements C2SMessageOrBuilder {
    // Use C2SMessage.newBuilder() to construct.
    private C2SMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2SMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2SMessage defaultInstance;
    public static C2SMessage getDefaultInstance() {
      return defaultInstance;
    }

    public C2SMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2SMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wangboo.nsgame.protocol.MessageProto.MessageId value = com.wangboo.nsgame.protocol.MessageProto.MessageId.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgId_ = value;
              }
              break;
            }
            case 18: {
              com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = c2SLogin_.toBuilder();
              }
              c2SLogin_ = input.readMessage(com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(c2SLogin_);
                c2SLogin_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.class, com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<C2SMessage> PARSER =
        new com.google.protobuf.AbstractParser<C2SMessage>() {
      public C2SMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2SMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.wangboo.nsgame.protocol.MessageId msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.wangboo.nsgame.protocol.MessageProto.MessageId msgId_;
    /**
     * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
     */
    public com.wangboo.nsgame.protocol.MessageProto.MessageId getMsgId() {
      return msgId_;
    }

    // optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;
    public static final int C2SLOGIN_FIELD_NUMBER = 2;
    private com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin c2SLogin_;
    /**
     * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
     */
    public boolean hasC2SLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
     */
    public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin getC2SLogin() {
      return c2SLogin_;
    }
    /**
     * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
     */
    public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder getC2SLoginOrBuilder() {
      return c2SLogin_;
    }

    private void initFields() {
      msgId_ = com.wangboo.nsgame.protocol.MessageProto.MessageId.C2SLoginId;
      c2SLogin_ = com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasC2SLogin()) {
        if (!getC2SLogin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, c2SLogin_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgId_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, c2SLogin_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wangboo.nsgame.protocol.C2SMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.class, com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.Builder.class);
      }

      // Construct using com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getC2SLoginFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = com.wangboo.nsgame.protocol.MessageProto.MessageId.C2SLoginId;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (c2SLoginBuilder_ == null) {
          c2SLogin_ = com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance();
        } else {
          c2SLoginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SMessage_descriptor;
      }

      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage getDefaultInstanceForType() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.getDefaultInstance();
      }

      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage build() {
        com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage buildPartial() {
        com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage result = new com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (c2SLoginBuilder_ == null) {
          result.c2SLogin_ = c2SLogin_;
        } else {
          result.c2SLogin_ = c2SLoginBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage) {
          return mergeFrom((com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage other) {
        if (other == com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasC2SLogin()) {
          mergeC2SLogin(other.getC2SLogin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (hasC2SLogin()) {
          if (!getC2SLogin().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wangboo.nsgame.protocol.C2SMessageProto.C2SMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.wangboo.nsgame.protocol.MessageId msgId = 1;
      private com.wangboo.nsgame.protocol.MessageProto.MessageId msgId_ = com.wangboo.nsgame.protocol.MessageProto.MessageId.C2SLoginId;
      /**
       * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
       */
      public com.wangboo.nsgame.protocol.MessageProto.MessageId getMsgId() {
        return msgId_;
      }
      /**
       * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
       */
      public Builder setMsgId(com.wangboo.nsgame.protocol.MessageProto.MessageId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.wangboo.nsgame.protocol.MessageId msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.wangboo.nsgame.protocol.MessageProto.MessageId.C2SLoginId;
        onChanged();
        return this;
      }

      // optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;
      private com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin c2SLogin_ = com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder> c2SLoginBuilder_;
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public boolean hasC2SLogin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin getC2SLogin() {
        if (c2SLoginBuilder_ == null) {
          return c2SLogin_;
        } else {
          return c2SLoginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public Builder setC2SLogin(com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin value) {
        if (c2SLoginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          c2SLogin_ = value;
          onChanged();
        } else {
          c2SLoginBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public Builder setC2SLogin(
          com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder builderForValue) {
        if (c2SLoginBuilder_ == null) {
          c2SLogin_ = builderForValue.build();
          onChanged();
        } else {
          c2SLoginBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public Builder mergeC2SLogin(com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin value) {
        if (c2SLoginBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              c2SLogin_ != com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance()) {
            c2SLogin_ =
              com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.newBuilder(c2SLogin_).mergeFrom(value).buildPartial();
          } else {
            c2SLogin_ = value;
          }
          onChanged();
        } else {
          c2SLoginBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public Builder clearC2SLogin() {
        if (c2SLoginBuilder_ == null) {
          c2SLogin_ = com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance();
          onChanged();
        } else {
          c2SLoginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder getC2SLoginBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getC2SLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder getC2SLoginOrBuilder() {
        if (c2SLoginBuilder_ != null) {
          return c2SLoginBuilder_.getMessageOrBuilder();
        } else {
          return c2SLogin_;
        }
      }
      /**
       * <code>optional .com.wangboo.nsgame.protocol.C2SLogin c2sLogin = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder> 
          getC2SLoginFieldBuilder() {
        if (c2SLoginBuilder_ == null) {
          c2SLoginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder>(
                  c2SLogin_,
                  getParentForChildren(),
                  isClean());
          c2SLogin_ = null;
        }
        return c2SLoginBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.wangboo.nsgame.protocol.C2SMessage)
    }

    static {
      defaultInstance = new C2SMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wangboo.nsgame.protocol.C2SMessage)
  }

  public interface C2SLoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string username = 1;
    /**
     * <code>required string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string password = 2;
    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.wangboo.nsgame.protocol.C2SLogin}
   */
  public static final class C2SLogin extends
      com.google.protobuf.GeneratedMessage
      implements C2SLoginOrBuilder {
    // Use C2SLogin.newBuilder() to construct.
    private C2SLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2SLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2SLogin defaultInstance;
    public static C2SLogin getDefaultInstance() {
      return defaultInstance;
    }

    public C2SLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2SLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.class, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<C2SLogin> PARSER =
        new com.google.protobuf.AbstractParser<C2SLogin>() {
      public C2SLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2SLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>required string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      username_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wangboo.nsgame.protocol.C2SLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wangboo.nsgame.protocol.C2SMessageProto.C2SLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.class, com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.Builder.class);
      }

      // Construct using com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.internal_static_com_wangboo_nsgame_protocol_C2SLogin_descriptor;
      }

      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin getDefaultInstanceForType() {
        return com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance();
      }

      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin build() {
        com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin buildPartial() {
        com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin result = new com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin) {
          return mergeFrom((com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin other) {
        if (other == com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wangboo.nsgame.protocol.C2SMessageProto.C2SLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string username = 1;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      // required string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wangboo.nsgame.protocol.C2SLogin)
    }

    static {
      defaultInstance = new C2SLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wangboo.nsgame.protocol.C2SLogin)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wangboo_nsgame_protocol_C2SMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wangboo_nsgame_protocol_C2SMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wangboo_nsgame_protocol_C2SLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wangboo_nsgame_protocol_C2SLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020C2SMessage.proto\022\033com.wangboo.nsgame.p" +
      "rotocol\032\017MessageId.proto\"|\n\nC2SMessage\0225" +
      "\n\005msgId\030\001 \002(\0162&.com.wangboo.nsgame.proto" +
      "col.MessageId\0227\n\010c2sLogin\030\002 \001(\0132%.com.wa" +
      "ngboo.nsgame.protocol.C2SLogin\".\n\010C2SLog" +
      "in\022\020\n\010username\030\001 \002(\t\022\020\n\010password\030\002 \002(\tB\021" +
      "B\017C2SMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wangboo_nsgame_protocol_C2SMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wangboo_nsgame_protocol_C2SMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wangboo_nsgame_protocol_C2SMessage_descriptor,
              new java.lang.String[] { "MsgId", "C2SLogin", });
          internal_static_com_wangboo_nsgame_protocol_C2SLogin_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wangboo_nsgame_protocol_C2SLogin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wangboo_nsgame_protocol_C2SLogin_descriptor,
              new java.lang.String[] { "Username", "Password", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wangboo.nsgame.protocol.MessageProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
