// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageId.proto

package com.wangboo.nsgame.protocol;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.wangboo.nsgame.protocol.MessageId}
   */
  public enum MessageId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>C2SLoginId = 1;</code>
     */
    C2SLoginId(0, 1),
    ;

    /**
     * <code>C2SLoginId = 1;</code>
     */
    public static final int C2SLoginId_VALUE = 1;


    public final int getNumber() { return value; }

    public static MessageId valueOf(int value) {
      switch (value) {
        case 1: return C2SLoginId;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageId>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageId>() {
            public MessageId findValueByNumber(int number) {
              return MessageId.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wangboo.nsgame.protocol.MessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageId[] VALUES = values();

    public static MessageId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageId(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.wangboo.nsgame.protocol.MessageId)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MessageId.proto\022\033com.wangboo.nsgame.pr" +
      "otocol*\033\n\tMessageId\022\016\n\nC2SLoginId\020\001B\016B\014M" +
      "essageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
